function save() {
    if (file_exists("User.sav")) file_delete("User.sav");
    ini_open("User.sav")
    ini_write_real("Save1", "levelFourEasyTime", obj_levelTracker.levelFourEasyTime);
    ini_write_real("Save1", "levelFourEasyChallengemodeClear", obj_levelTracker.levelFourEasyChallengeModeClear);
    ini_write_real("Save1", "levelFourMediumTime", obj_levelTracker.levelFourMediumTime);
    ini_write_real("Save1", "levelFourMediumChallengemodeClear", obj_levelTracker.levelFourMediumChallengeModeClear);
    ini_write_real("Save1", "levelFourHardTime", obj_levelTracker.levelFourHardTime);
    ini_write_real("Save1", "levelFourHardChallengemodeClear", obj_levelTracker.levelFourHardChallengeModeClear);
    ini_write_real("Save1", "levelFourChallengemodeClear", obj_levelTracker.levelFourChallengeModeClear);
    ini_write_real("Save1", "evolvedMonsterTutorialOneCleared", obj_levelTracker.evolvedMonsterTutorialOneCleared);
    ini_write_real("Save1", "evolvedMonsterTutorialTwoCleared", obj_levelTracker.evolvedMonsterTutorialTwoCleared);
    ini_write_real("Save1", "mineTutorialCleared", obj_levelTracker.mineTutorialCleared);
    ini_write_real("Save1", "monsterTutorialCleared", obj_levelTracker.monsterTutorialCleared);
    ini_write_real("Save1", "probeTutorialCleared", obj_levelTracker.probeTutorialCleared);
    ini_write_real("Save1", "anglerTutorialCleared", obj_levelTracker.anglerTutorialCleared);
    ini_write_real("Save1", "movementTutorialCleared", obj_levelTracker.movementTutorialCleared);
	ini_write_real("Save1", "swimmerCosmetic", obj_microtransactions.swimmerSkin);
    ini_write_real("Save1", "lightCosmetic", obj_microtransactions.newLightEffect);
    ini_write_real("Save1", "swimmerSkinBought", obj_microtransactions.swimmerSkinBought);
    ini_write_real("Save1", "lightCosmeticBought", obj_microtransactions.lightCosmeticBought);
    ini_write_real("Save1", "mouseAndArrowKeyControls", obj_options.mouseAndArrowKeyControls);
    ini_write_real("Save1", "WASDControls", obj_options.WASDControls);
    ini_write_real("Save1", "arrowKeyControls", obj_options.arrowKeyControls);
    ini_write_real("Save1", "decreaseReactionTimeRequired", obj_options.decreaseReactionTimeRequired);
    ini_write_real("Save1", "textToSpeak", obj_options.textToSpeak);
    ini_write_real("Save1", "objectiveReminder", obj_options.objectiveReminder);
    ini_write_real("Save1", "showNumberOfPollutantsPictorially", obj_options.showNumberOfPollutantsPictorially);
    ini_write_real("Save1", "timeAnnoucements", obj_options.timeAnnoucements);
    ini_write_real("Save1", "changeFontToAriel", obj_options.changeFontToAriel);
    ini_write_real("Save1", "removeBackgroundNoise", obj_options.removeBackgroundNoise);
    ini_write_real("Save1", "waitTimeInsteadOfDeath", obj_options.waitTimeInsteadOfDeath);
    ini_write_real("Save1", "destroyEnemiesWithBarriers", obj_options.destroyEnemiesWithBarriers);
	ini_write_real("Save1", "playALevelBackToBack", obj_options.playALevelBackToBack);
	ini_write_real("Save1", "monsterAvoidanceAbility", obj_options.monsterAvoidanceAbility);
    ini_write_real("Save1", "sonar", obj_options.sonar);
	ini_write_real("Save1", "closedCaptioning", obj_options.closedCaptioning);
	ini_close();
}