function save() {
    if (file_exists("User.sav")) file_delete("User.sav");
    ini_open("User.sav")
    ini_write_real("Save1", "levelFourEasyTime", obj_levelTracker.levelFourEasyTime);
    ini_write_real("Save1", "levelFourEasyChallengemodeClear", obj_levelTracker.levelFourEasyChallengeModeClear);
    ini_write_real("Save1", "levelFourMediumTime", obj_levelTracker.levelFourMediumTime);
    ini_write_real("Save1", "levelFourMediumChallengemodeClear", obj_levelTracker.levelFourMediumChallengeModeClear);
    ini_write_real("Save1", "levelFourHardTime", obj_levelTracker.levelFourHardTime);
    ini_write_real("Save1", "levelFourHardChallengemodeClear", obj_levelTracker.levelFourHardChallengeModeClear);
    ini_write_real("Save1", "levelFourChallengemodeClear", obj_levelTracker.levelFourChallengeModeClear);
    ini_write_real("Save1", "swimmerCosmetic", obj_microtransactions.swimmerSkin);
    ini_write_real("Save1", "lightCosmetic", obj_microtransactions.newLightEffect);
    ini_write_real("Save1", "swimmerSkinBought", obj_microtransactions.swimmerSkinBought);
    ini_write_real("Save1", "lightCosmeticBought", obj_microtransactions.lightCosmeticBought);
    ini_write_real("Save1", "normal", obj_options.normal);
    ini_write_real("Save1", "leftHanded", obj_options.leftHandControls);
    ini_write_real("Save1", "rightHanded", obj_options.rightHandControls);
    ini_write_real("Save1", "poorReactivity", obj_options.poorReactivity);
    ini_write_real("Save1", "blindMode", obj_options.blindMode);
    ini_write_real("Save1", "ADHD", obj_options.ADHD);
    ini_write_real("Save1", "dyscalculia", obj_options.dyscalculia);
    ini_write_real("Save1", "executiveFunctioning", obj_options.executiveFunctioning);
    ini_write_real("Save1", "dyslexia", obj_options.dyslexia);
    ini_write_real("Save1", "evolvedMonsterTutorialOneCleared", obj_levelTracker.evolvedMonsterTutorialOneCleared);
    ini_write_real("Save1", "evolvedMonsterTutorialTwoCleared", obj_levelTracker.evolvedMonsterTutorialTwoCleared);
    ini_write_real("Save1", "mineTutorialCleared", obj_levelTracker.mineTutorialCleared);
    ini_write_real("Save1", "monsterTutorialCleared", obj_levelTracker.monsterTutorialCleared);
    ini_write_real("Save1", "probeTutorialCleared", obj_levelTracker.probeTutorialCleared);
    ini_write_real("Save1", "anglerTutorialCleared", obj_levelTracker.anglerTutorialCleared);
    ini_write_real("Save1", "movementTutorialCleared", obj_levelTracker.movementTutorialCleared);
    ini_write_real("Save1", "auditoryProcessingDisorder", obj_options.auditoryProcessingDisorder);
    ini_write_real("Save1", "alternativePunishment", obj_options.alternativePunishment);
    ini_write_real("Save1", "variableObjectives", obj_options.variableObjectives);
	ini_write_real("Save1", "indirectCompetition", obj_options.indirectCompetition);
	ini_write_real("Save1", "conflictResolutionAlternative", obj_options.conflictResolutionAlternatives);
    ini_write_real("Save1", "sonar", obj_options.sonar);
	ini_write_real("Save1", "closedCaptioning", obj_options.closedCaptioning);
	ini_close();
}